### ISSUE TITLE
Moving over the TSQL-version as well?

### ISSUE THREAD

**Issue by enkelmedia** [Valien/ExpressMaintenance#1]
Hi!

What would you say about moving over the TSQL-version as well? I can send over a PR if you would like? Have it live in it's own branch?

**Comment by enkelmedia** [comment]
This: http://expressmaint.codeplex.com/releases/view/20228

**Comment by Valien** [comment]
Hi! I am not actively working/maintaining this project anymore. If you want to do a fork and add the TSQL go for it!
